### ISSUE TITLE
L3MON APK building error...proot info: vpid 1: terminated with signal 11

### ISSUE THREAD

**Issue by whoamirk** [h4ck3r0/Lemon-termux#10]
After starting lemon server on my termux then I can login successfully on lemon server now if I click build apk I got 👉 👇👇👇👈
ERROR Build Failed - Build Command Failed - Command failed: proot java -jar "/data/data/com.termux/files/usr/share/lemon/app/factory/apktool.jar" b "/data/data/com.termux/files/usr/share/lemon/app/factory/decompiled" -o "/data/data/com.termux/files/usr/share/lemon/assets/webpublic/build.apk"
proot error: '/data/data/com.termux/files/usr/share/jdk8/bin/java' is a 64-bit program whereas this version of proot handles 32-bit programs only                                                                 proot info: vpid 1: terminated with signal 11
👉👉👉👇👇👇👈👈👈
This error... please help me..😭😭I also install java
![Screenshot_2023-08-04-05-37-26-881_com android chrome](https://github.com/h4ck3r0/Lemon-termux/assets/137401490/f6f32339-f8f3-4459-b4af-a001c752ce6b)
![Screenshot_2023-08-04-05-33-21-560_com termux](https://github.com/h4ck3r0/Lemon-termux/assets/137401490/6e3c00e7-d4ac-47c0-a8a9-0915e9e13465)

**Comment by h4ck3r0** [comment]
Before  creating issue give star to my repo and atleast follow all steps, you don't install java 8 install it
