### ISSUE TITLE
Java error 

### ISSUE THREAD

**Issue by abhinav938** [h4ck3r0/Lemon-termux#12]
ERROR Build Failed - Build Command Failed - Command failed: proot java -jar "/data/data/com.termux/files/usr/share/lemon/app/factory/apktool.jar" b "/data/data/com.termux/files/usr/share/lemon/app/factory/decompiled" -o "/data/data/com.termux/files/usr/share/lemon/assets/webpublic/build.apk"
java.io.IOException: No such file or directory

![Screenshot_2023_1108_133324](https://github.com/h4ck3r0/Lemon-termux/assets/79570013/419207be-79dc-44cc-91eb-696fd0c3288e)

**Comment by h4ck3r0** [comment]
Install java 8

**Comment by abhinav938** [comment]
I already installed Java 8
