### ISSUE TITLE
Apk build Error please help me 

### ISSUE THREAD

**Issue by Shoaibkhanlodhi** [h4ck3r0/Lemon-termux#13]
I'm facing these issue on my Termux. Please help me to fix it.

23/11/2023, 02:05:35 => ERROR | Build Failed - Build Command Failed - Command failed: proot java -jar "/data/data/com.termux/files/usr/share/lemon/app/factory/apktool.jar" b "/data/data/com.termux/files/usr/share/lemon/app/factory/decompiled" -o "/data/data/com.termux/files/usr/share/lemon/assets/webpublic/build.apk" java.io.IOException: No such file or directory

**Comment by Eugenexjay** [comment]
Install "Java openjdk-8" on termux

Install now ==> https://github.com/SHivnaTH13/Termux-OpenJDK
