### ISSUE TITLE
APK Builder. Error

### ISSUE THREAD

**Issue by Eugenexjay** [h4ck3r0/Lemon-termux#14]
└───>  lemon
Server Started!
http://localhost:22533
ERROR Build Failed - Build Command Failed - Command failed: proot java -jar "/data/data/com.termux/files/usr/share/lemon/app/factory/apktool.jar" b "/data/data/com.termux/files/usr/share/lemon/app/factory/decompiled" -o "/data/data/com.termux/files/usr/share/lemon/assets/webpublic/build.apk"

I followed all your steps in the
installation of Lemon-termux and it was a success. But in the Java-termux installation, I followed all your steps in the video but there is still an error, I don't know what to do. Can you help me please ? 🥺

**Comment by h4ck3r0** [comment]
Bro java is not supported by all phone but trust me it will work on another if it's installed successfully and don't forget to check java version
