### ISSUE TITLE
Help me please 🥺

### ISSUE THREAD

**Issue by Eugenexjay** [h4ck3r0/Lemon-termux#17]
Help me please ...... 🙏 To install the Java openjdk-8 version "1.8.0_152" on termux.

! Like this !
![Screenshot_20231209-185758.png](https://github.com/h4ck3r0/Lemon-termux/assets/120492432/6ccd656e-845e-4042-9147-667bd865d1ae)

==============================

Bro, everything I did to install Java. But it's still an error and what is it that I installed java versions to make APK builder work. I hope you can help me bro to install your java version.

This is the java openjdk-8 version I used !
[!] ==> https://github.com/SHivnaTH13/Termux-OpenJDK

==============================

[√] APK Builder success.
![Screenshot_20231220-235401.png](https://github.com/h4ck3r0/Lemon-termux/assets/120492432/6be13a11-0036-4f77-bee3-ed78361ba429)

==============================

[!] But when I install L3mon.apk file error
![Screenshot_20231220-235558.png](https://github.com/h4ck3r0/Lemon-termux/assets/120492432/a541bb59-801a-4ec4-ab3b-01e507b38ac7)

I hope you can give me a command script to install Java openjdk8 version "1.8.0_152". Please 🥺 🙏 help me bro ???

**Comment by h4ck3r0** [comment]
Process is same as shown in video and the fact is java 8 is not supported on all Android phones, try my java may work else try on another phone
