### ISSUE TITLE
After java is installed. And run the java error !

### ISSUE THREAD

**Issue by Eugenexjay** [h4ck3r0/Lemon-termux#18]
I have already installed your java version in termux. But when I type the command "java" or "proot java" this is what is shown !

[1]
![Screenshot_20231223-172055.png](https://github.com/h4ck3r0/Lemon-termux/assets/120492432/a86f8a93-31fa-4042-b0af-03bc6006eab7)

[2]
![Screenshot_20231223-171810.png](https://github.com/h4ck3r0/Lemon-termux/assets/120492432/6b6e50f5-63b4-4bcb-b02b-9446455e653e)

Help me bro please !

**Comment by h4ck3r0** [comment]
Java will not work in your phone
