### ISSUE TITLE
Error in APK building 

### ISSUE THREAD

**Issue by Annxhilator** [h4ck3r0/Lemon-termux#5]
ERROR Build Failed - Build Command Failed - Command failed: proot java -jar "/data/data/com.termux/files/usr/share/lemon/app/factory/apktool.jar" b "/data/data/com.termux/files/usr/share/lemon/app/factory/decompiled" -o "/data/data/com.termux/files/usr/share/lemon/assets/webpublic/build.apk"
32 bit support is deprecated. Apktool will not support 32bit on v3.0.0.                                                         brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_55685349688513406591086126838425319639.tmp, p, --forced-package-id, 127, --min-sdk-version, 11, --target-sdk-version, 24, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /data/data/com.termux/files/usr/tmp/APKTOOL6446407559068244608.tmp, -e, /data/data/com.termux/files/usr/tmp/APKTOOL17754402438540841165.tmp, -0, arsc, -I, /data/data/com.termux/files/home/.local/share/apktool/framework/1.apk, -S, /data/data/com.termux/files/usr/share/lemon/app/factory/decompiled/res, -M, /data/data/com.termux/files/usr/share/lemon/app/factory/decompiled/AndroidManifest.xml]

That shows me everytime, already tried to reinstall.[![Screenshot_20230222-181251.png](https://user-images.githubusercontent.com/105570214/220760239-4659338d-d028-4f1e-8099-118e150aa430.png)

**Comment by h4ck3r0** [comment]
Watch Video and install java without it will not work

**Comment by Annxhilator** [comment]
Looks like you didn't even read my issue. In the video u don't say anything
about java, u even got an error building the APK too. Stop closing issues
like it's nothing come on dude.

**Comment by h4ck3r0** [comment]
I already told that i will make video on build error , that's java  video, in the end of java installation video I show to create lemon apk, please check it out before creating issue thank you.  

 Watch :- https://youtu.be/MgpGfOapqn0

And i already update Readme, you can watch video from there too

Sorry for the inconvenience

Regards :- H4Ck3R
