### ISSUE TITLE
Error Builder Commands, Here The Log.

### ISSUE THREAD

**Issue by F3ndySec** [h4ck3r0/Lemon-termux#7]
14/07/2023, 03:45:19 => ERROR | Build Failed - Build Command Failed - Command failed: proot java -jar "/data/data/com.termux/files/usr/share/lemon/app/factory/apktool.jar" b "/data/data/com.termux/files/usr/share/lemon/app/factory/decompiled" -o 
"/data/data/com.termux/files/usr/share/lemon/assets/webpublic/build.apk" /data/data/com.termux/files/usr/bin/sh: 1: proot: not found

14/07/2023, 03:45:19 => ERROR | Build Failed - Unable to spawn Java - Error: spawn java ENOENT
/
/

**Comment by h4ck3r0** [comment]
I already added java installation video without java it will not work, install java from comment box command

**Comment by F3ndySec** [comment]
Already installed java bro

**Comment by F3ndySec** [comment]
I installed java from comment box bro

**Comment by h4ck3r0** [comment]
Check issue will be solved no doubt, I get comments for this issue per day but the solution is same java installing, check further java is installed correctly or not

**Comment by F3ndySec** [comment]
Okay, thanks for information, i will try it!
