### ISSUE TITLE
Apktool will not support 32bit

### ISSUE THREAD

**Issue by F3ndySec** [h4ck3r0/Lemon-termux#8]
Apktool will not support 32bit on v3.0.0., how to fix

**Comment by h4ck3r0** [comment]
No use of apktool only java

**Comment by F3ndySec** [comment]
ERROR Build Failed - Build Command Failed - Command failed: proot java -jar "/data/data/com.termux/files/usr/share/lemon/app/factory/apktool.jar" b "/data/data/com.termux/files/usr/share/lemon/app/factory/decompiled" -o "/data/data/com.termux/files/usr/share/lemon/assets/webpublic/build.apk"
32 bit support is deprecated. Apktool will not support 32bit on v3.0.0.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_154611255469267198908012517551031819094.tmp, p, --forced-package-id, 127, --min-sdk-version, 11, --target-sdk-version, 24, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /data/data/com.termux/files/usr/tmp/APKTOOL7322096634298821540.tmp, -e, /data/data/com.termux/files/usr/tmp/APKTOOL10477505582881436544.tmp, -0, arsc, -I, /data/data/com.termux/files/home/.local/share/apktool/framework/1.apk, -S, /data/data/com.termux/files/usr/share/lemon/app/factory/decompiled/res, -M, /data/data/com.termux/files/usr/share/lemon/app/factory/decompiled/AndroidManifest.xml] here the full output

**Comment by F3ndySec** [comment]
uninstall apktool?

**Comment by h4ck3r0** [comment]
Which platform are you using? This is only for Android

**Comment by F3ndySec** [comment]
I use Termux, Android

**Comment by h4ck3r0** [comment]
Search, Android architecture tool and check your phone architecture
